### PR TITLE
KPNO install fix

### PR DESCRIPTION
**Pull request by sybenzvi**
A few changes to enable installation of desiconda packages on desi-7, intended to address the problems raised in #59:
- Disable pip installation of `hpsspy` and `mpi4py`.
- Disable installation of `specex` (requires BLAS libraries not installed) and QuasarNP.
- Enable installation of `nightwatch` as a module.

### CODE REVIEW

**Comment by marcelo-alvarez** [comment]
@sybenzvi thanks for doing this, it looks great.

Removing specex and QuasarNP should be fine in the bootstrap — once we get specex finding the right libraries, we can put it back in and install it manually as opposed to in the bootstrap, with QuasarNP on a need-to-use basis.

Let's wait until you have a desiconda that is working in practice (which I assume you don’t quite have yet?). For example I’m surprised there are no settings you need to set in a `conf/kpno-env.sh` (which doesn’t exist but would be analogous to `conf/nersc-env.sh`).

**Comment by sybenzvi** [comment]
> Let's wait until you have a desiconda that is working in practice (which I assume you don’t quite have yet?). For example I’m surprised there are no settings you need to set in a `conf/kpno-env.sh` (which doesn’t exist but would be analogous to `conf/nersc-env.sh`).

Good point, there are a few things that should be set (for example, there is no `desi` group on desi-7).

**Comment by marcelo-alvarez** [comment]
@sybenzvi checking in -- please let me know if I can help in any way with this. If I recall correctly, the plan is to use this branch to install a working desiconda at KPNO and, once that works, to review and merge the changes into main (mostly to ensure that it doesn't break desiconda at Perlmutter or make future changes more difficult than necessary, I think). @sbailey please let us know if you have any input about this. Thanks.

**Comment by sbailey** [comment]
@sybenzvi heads up: I'm going to merge this now so that we can use the mamba stuff for NERSC installs too.  The rest is isolated to KPNO specific pieces.  If those need further updates to work at KPNO, please open a new PR with that.

**Comment by sybenzvi** [comment]
Thanks @sbailey, any further updates needed for KPNO will be in a fresh PR.

**Pull request merged**
